apply plugin: 'com.android.application'

android {
    namespace 'org.ashlands.game'
    compileSdk 34

    defaultConfig {
        applicationId 'org.ashlands.game'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '0.1.0'
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86_64'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    sourceSets {
        main {
            manifest.srcFile 'src/main/AndroidManifest.xml'
            java.srcDirs = ['src/main/java']
            assets.srcDirs = ['src/main/assets']
            jni.srcDirs = []
        }
    }

    ndkVersion '25.2.9519653'

    externalNativeBuild {
        ndkBuild {
            path 'src/main/jni/Android.mk'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
